/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:        'var(--cd-bg)',
        surface:   'var(--cd-surface)',
        elev:      'var(--cd-elev)',
        'elev-2':  'var(--cd-elev-2)',
        border:    'var(--cd-border)',
        'border-hi': 'var(--cd-border-hi)',
        text:      'var(--cd-text)',
        'text-dim':   'var(--cd-text-dim)',
        'text-mute':  'var(--cd-text-mute)',
        'text-ghost': 'var(--cd-text-ghost)',
        'text-on-accent': 'var(--cd-text-on-accent)',
        accent:        'var(--cd-accent)',
        'accent-hover': 'var(--cd-accent-hover)',
        'accent-bg':   'var(--cd-accent-bg)',
        'accent-bg-hi': 'var(--cd-accent-bg-hi)',
        'accent-border': 'var(--cd-accent-border)',
        green:  'var(--cd-green)',
        yellow: 'var(--cd-yellow)',
        orange: 'var(--cd-orange)',
        red:    'var(--cd-red)',
        'green-soft':  'var(--cd-green-soft)',
        'yellow-soft': 'var(--cd-yellow-soft)',
        'orange-soft': 'var(--cd-orange-soft)',
        'red-soft':    'var(--cd-red-soft)',
        'row-hover':   'var(--cd-row-hover)',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs':['10px',{lineHeight:'14px'}], xs:['11px',{lineHeight:'16px'}],
        sm:['12px',{lineHeight:'18px'}], base:['13px',{lineHeight:'20px'}],
        md:['14px',{lineHeight:'20px'}], lg:['15px',{lineHeight:'22px'}],
        xl:['17px',{lineHeight:'24px'}], '2xl':['20px',{lineHeight:'28px'}],
        '3xl':['28px',{lineHeight:'32px'}], '4xl':['44px',{lineHeight:'48px'}],
      },
      letterSpacing: { tight:'-0.02em', base:'-0.005em', wide:'0.04em', wider:'0.08em', caps:'0.12em' },
      borderRadius: { none:'0', xs:'2px', sm:'3px', DEFAULT:'4px', lg:'6px', pill:'999px' },
      boxShadow: { sm:'var(--cd-shadow-sm)', DEFAULT:'var(--cd-shadow-md)', lg:'var(--cd-shadow-lg)' },
    },
  },
  plugins: [],
};
