version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: compliance_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: compliance_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      LICENSE_SERVER_URL: ${LICENSE_SERVER_URL}
      COMPANY_LICENSE_KEY: ${COMPANY_LICENSE_KEY}
    depends_on:
      - db
    ports:
      - "8080:8000"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend/apps/compliance-frontend
    container_name: compliance_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  uploads_data:
